
[loader]
entrypoint = "file:{{ gramine.libos }}"
log_level = "error"
argv_src_file = "file:/app/args.txt"
[loader.env]
LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}"
MALLOC_ARENA_MAX = "1"
mode = { passthrough = true }

[libos]
entrypoint = "/usr/bin/python3"


[fs]
mounts = [
    { path = "/tmp", uri = "file:/tmp", type = "tmpfs" },
    { path = "/etc", uri = "file:/etc" },
    { path = "/usr", uri = "file:/usr" },
    { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
    { path = "{{ arch_libdir }}", uri = "file:{{ arch_libdir }}" },
    { path = "/app", uri = "file:/app" },
    { path = "/data", uri = "file:/data", type = "encrypted", key_name = "_sgx_mrenclave" },
]


[sgx]
rpc_thread_num = 16
thread_num = 16
enclave_size = "2G"
isvprodid = 1
isvsvn = 1
trusted_files = [
    "file:{{ gramine.libos }}",
    "file:{{ gramine.runtimedir()}}/",
    "file:{{ arch_libdir }}/",
    "file:/usr/lib/python3.10/",
    "file:/usr/bin/python3",
    "file:/etc/localtime",
    "file:/etc/mime.types",
]
allowed_files = [
    "file:/usr/local/lib/python3.10/",
    "file:/usr/lib/python3/dist-packages/",
    "file:/app/",

]
